### ISSUE TITLE
It seems that the modified CODAL code is not properly applied as a runtime HEX file.

### ISSUE THREAD

**Issue by OpusK** [microsoft/pxt-robotis#38] opened 2020-03-26 10:59 UTC
Hi, @pelikhan, @mmoskal.

**Describe the bug**
Although the member function of a specific class not implemented in codal-core was implemented in a class that inherited the class, MakeCode does not link the proper runtime HEX file.
Of course, these work without problems when using only the CODAL build system.

The CODAL code related to the previously modified Serial package or the newly added DYNAMIXEL worked well.
Is there anything different about the core package?

**To Reproduce**
1. [Modify member function of CODAL Core Class](https://github.com/ROBOTIS-GIT/codal-nrf52/blob/develop/source/NRF52Pin.cpp#L402)
2. Commit & Push to GitHub.
3. ```pxt serve``` or ```pxt serve --localbuild```
4. Write code at MakeCode (eg. MakeCode ROBOTIS)
```ts
forever(function () {
    serial.writeValue("V", pins.VOLTAGE.analogRead())
    pause(500)
})
```
5. Download & Upload to target board (The code has changed, so it must be compiled, not the cached hex file, but it is not recompiled. If you delete the "built/hexcache" folder and clear the browser's cache, it will be recompiled, but the hex hash value is the same.)
6. Look at the behavior of the board (The changed member function was not applied)

**Expected behavior**
I wrote it as a more specific example.
1. The getAnalogValue() function in Pin.h of codal-core is not implemented.
2. Therefore, we implemented getAnalogValue() in NRF52Pin of codal-nrf52.
3. We implemented [to print 4444](https://github.com/ROBOTIS-GIT/codal-nrf52/blob/develop/source/NRF52Pin.cpp#L402) instead of -1013(DEVICE_NOT_IMPLEMENTED) value.
4. Now it is applied. (We have confirmed that this compiles normally through various methods and creates a .hex file in the dockercodal or codal folder. We made sure that this compiles normally, such as by creating additional functions, inserting error codes or checking the .map file.)
5. Now, the value that was output as -1013 should be output as 4444. But...

**Screenshots**
- Before
```cpp
int NRF52Pin::getAnalogValue()
{
    return DEVICE_NOT_IMPLEMENTED;
}
```

- After
```cpp
int NRF52Pin::getAnalogValue()
{
    int data = 4444;
    return data;//DEVICE_NOT_IMPLEMENTED;
}
```

![image](https://user-images.githubusercontent.com/18085958/77638409-73670700-6f9a-11ea-8d53-5463d4e3aa4c.png)

- But...
![image](https://user-images.githubusercontent.com/18085958/77638258-3569e300-6f9a-11ea-9f50-d47b7f828422.png)

**Desktop:**
 - OS: Windows10 Pro
 - Browser: chrome / NAVER whale(based on chrome)
 - Version: chrome 80.0.3987.149

**Additional context**

**Comment by mmoskal** [comment] 2020-03-28 00:30
The field `branch` [here](https://github.com/microsoft/pxt-robotis/blob/master/pxtarget.json#L154) really needs to be a tag to get proper caching. I know the name is confusing.

In your codal folder, where you were doing your implementation, run `./build.py -l` - this will create a new tag in the target ( https://github.com/ROBOTIS-GIT/codal-cm300 ). Then put that tag in `branch` field.

Let me know if that helps!

**Comment by mmoskal** [comment] 2020-03-28 00:31
Also, make sure to use `./build -l` and not create tag with `git tag` - the `build.py` will also link to correct versions in all dependent repos.

**Comment by ajtwlsdlqp** [comment] 2020-03-30 06:21
Hello, @mmoskal  
Thanks for help 

**Describe the bug**
Previously, when I added a new accelerometer, I manually pasted the fix code into the dockercodal subfolder and tested it without uploading it to github.

In this process, the corrected code is reflected without any problems, so we test it in the same way and try to upload it once the problem is solved.

Does this method matter in any way?

In case of using `./build.py -l`, the suggested solution
('missing checkin in', 'D: \\ Path ~') complete with an error.
and still not fix "DEVICE NOT IMPLEMENTED"

**To reproduce**
Steps to reproduce the behavior : 

1. The commands of `pxt clean`,`pxt-cleangen`, and `pxt serve --localbuild` were sequentially executed in the pxt-robotis local git folder.

2. Move into pxt-robotis/lib/robotis-cm-300/built/dockercodal
and, do `python ./build.py -l`
++ just input command  `./build.py -l` cmd monitor flash shortly and nothing change.

3. complete with an error ('missing checkin', 'D: path ~ ')

4. no change 
![image](https://user-images.githubusercontent.com/10431571/77879491-86792000-7295-11ea-80fa-953942654dee.png)

**Expected behavior**
Nothing has been reflected and remains the same.

**Screenshots**
1. test based on codal local git floder
![image](https://user-images.githubusercontent.com/10431571/77880306-50d53680-7297-11ea-810b-99bc3563339e.png)

2. it is working well
![image](https://user-images.githubusercontent.com/10431571/77880236-21bec500-7297-11ea-9a7f-9832b24e2049.png)

3. pasted updated `NRF52Pin::getAnalogValue` function code to dockercodal subfolder and do 'pxt builddaldts', 'pxt serve --localbuild'

4. test by this block
![image](https://user-images.githubusercontent.com/10431571/77880952-c8579580-7298-11ea-92f6-0a8140df6077.png)

5. but...
![image](https://user-images.githubusercontent.com/10431571/77880990-dc9b9280-7298-11ea-9017-23fe812d9cb5.png)

**Desktop:**

OS: Windows10 Pro
Browser: chrome
Version: chrome 80.0.3987.149

**Comment by mmoskal** [comment] 2020-03-30 15:03
It's best to test locally like you did before, without `./build.py -l`. The `./build.py -l` is needed to publish the fix at the end.

To test locally, I usually build from command line. 

First, I suggest you add the following environment variables to your computer setup:

```
PXT_FORCE_LOCAL=1
PXT_RUNTIME_DEV=1
PXT_ASMDEBUG=1
```

The first one will force a non-cloud build, the second will force re-running `cmake` on every build - this is useful if you make changes in codal, and the third adds additional debug information to generated `binary.asm` (you may not need that, but it doesn't hurt).

Then, head to `pxt-robotis/projects/my-project`. You can use an existing project created from `localhost:3232` or create a new one. The `pxt.json` should be modified to look something like this:

```json
{
    "name": "my-project",
    "dependencies": {
        "robotis-cm-300": "file:../../libs/robotis-cm-300"
    },
    "description": "",
    "files": [
        "main.ts"
    ]
}
```

The crucial part is `"file:../../libs/..."` instead of `"*"` - this will let you modify .cpp files in your target and pxt-common-packages and have these be picked up by build.

BTW, never edit files under `built/dockercodal/pxtapp` - these will be overwritten.

If you edited `pxtarget.json`, delete `pxt-robotis/built/target*` that you may have left from previous `pxt serve` or `pxt buildtarget`.

Now, you should be ready to build, in `pxt-robotis/projects/my-project` just run `pxt`.

Then, run `code build/dockercodal/libraries/*`, checkout appropriate branches in all repos (usually master), do your changes, run `pxt` to test, and eventually do the steps with `./build.py -l` and editing `pxtarget.json` to publish the fixes.

Let me know if this helps!

**Comment by mmoskal** [comment] 2020-03-30 15:04
BTW, the critical bit is building your `.uf2` file using `pxt` command, not the web app.

**Comment by ajtwlsdlqp** [comment] 2020-03-31 06:39
@mmoskal.

hello, mmoskal.
It was very helpful.

It seems that the problem occurred because the changes were not reflected as the cache was twisted.

Thank you.

**Comment by pelikhan** [comment] 2020-04-03 15:32
I am closing this. Please reopen if the issue continues.

**Closed as completed by pelikhan** 2020-04-03 15:32 UTC
